name: znc-arubislander
version: "1.6.5-snap3"
summary: advanced modular IRC bouncer
description: |
 znc is an IRC proxy. It runs as a daemon and connects to IRC server,
 then allows you to connect from a workstation and work as the user that
 is logged in to the IRC server. After you disconnect, it maintains the
 connection to the server. It acts like any normal IRC server, so you can
 use any IRC client to connect to it.
 .
 Some of its features include support for multiple users, multiple clients,
 and multiple IRC servers; playback buffers to catch up with what happened
 while you were detached, SSL encryption, DCC proxying, and a plugin
 interface with many plugins supporting other features.

confinement: strict
grade: devel

apps:
  znc:
    command: znc -f -r
    daemon: simple
    plugs: [network, network-bind, home]

parts:
  znc:
    plugin: autotools
    source: https://github.com/znc/znc.git
    source-tag: znc-1.6.5
    configflags:
      - '--enable-python'
      - '--enable-perl'
      - '--prefix=/usr/'
    build-packages:
      - python3-dev
      - libperl-dev
      - swig
      - pkg-config
      - cmake
      - automake
      - autoconf
      - libssl-dev
      - libicu-dev
      - zlib1g-dev
    prepare: |
      #!/bin/bash -ex
      patch -p1 < ../../../modules-dir-relative-snap-dir.patch

  znc-config:
    plugin: dump
    source: ./includes

  znc-push:
    plugin: make
    source: https://github.com/jreese/znc-push.git
    after: [znc]
    build-packages:
      - ca-certificates
    build: |
      #!/bin/bash -ex
      env PATH="../../../parts/znc/install/usr/bin:$PATH" make
      cp push.so ../../../stage/usr/share/znc/modules
